version: '3.4'

services:
  app:
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 3000:3000
    container_name: app
    stdin_open: true
    volumes:
      - .:/app