version: '3.4'

networks:
  react:

services:
  react-service:
    build: 
      context: .
      dockerfile: ./docker/react/Dockerfile
    ports:
      - 3000:3000
    container_name: react
    stdin_open: true
    volumes:
      - ./app:/app
      - /app/node_modules
    networks:
      - react