version: '3.4'

networks:
  react:

services:
  react-service:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: react
    stdin_open: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules